### ISSUE TITLE
Just FYI

### ISSUE THREAD

**Issue by xwize** [dangmoody/HLML#33] opened 2020-08-08 17:42 UTC
The zip on the releases page isn't actually a zip. I could get it extracted with 7z but Windows complained.

**Comment by dangmoody** [comment] 2020-08-08 18:24
Hi, thanks for submitting this issue!

So I think I know what's going on here.  I have a script that makes releases for me (puts all source files etc. into an archive which I can then drag-and-drop onto the release draft page) and it uses 7-zip to do this.  I think what's happening is that 7-zip is making a ".7z" archive but then I give it a ".zip" extension instead.

I'm not 100% sure how to combat that (.zip would be most ideal I think) because last I checked there wasn't that many 7-zip command line arguments that were relevant to me, but I'll have another look and see what I can find.

In the mean time I'm afraid you'll be having to unzip via 7-zip or WinRAR.  Apologies.

**Comment by dangmoody** [comment] 2020-08-08 19:08
So I went back through the release script and my batch writing skills have come on a bit since I initially wrote that.  =)

I've been able to reproduce your problem and I've attached a release .zip that was created through my updated release script.  It works for me, would you be able to confirm/deny for me please?

[hlml_1.1.zip](https://github.com/dangmoody/HLML/files/5046103/hlml_1.1.zip)

**Comment by xwize** [comment] 2020-08-08 19:11
Yep it works beautifully now. Thanks for making the library

**Comment by dangmoody** [comment] 2020-08-08 19:14
You're very welcome.  =)

Thanks for finding this, I've used 7-zip exclusively for the last 10 years so there was no way I would've found this.

I'll update the 1.1 release zip with the fixed archive and then close this.

**Closed** 2020-08-08 19:30 UTC
Labels: bug
